### PR TITLE
Add a new branch for lua5.1

### PR DESCRIPTION
**Pull request by daizeng1984**
Checklist
* [X] Used a fork of the feedstock to propose changes
* [x] Bumped the build number (if the version is unchanged)
* [X] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [X] Ensured the license file is being packaged.

When building some package we need lua5.1. e.g. https://github.com/conda-forge/staged-recipes/pull/12493

### CODE REVIEW

**Comment by daizeng1984** [comment]
@conda-forge-admin, please rerender

**Comment by daizeng1984** [comment]
@jerowe This PR is ready for review. Thanks!

**Comment by benjaminrwilson** [comment]
Hi @daizeng1984, was there anything blocking this?

**Comment by daizeng1984** [comment]
> Hi @daizeng1984, was there anything blocking this?

I don't have PR write access and now it has been a long time since ...

**Comment by izahn** [comment]
Since this PR has gone stale I suggest closing it and making a new one starting from the current master branch. 

If I were doing it I would look at the Arch linux recipe as an example: https://github.com/archlinux/svntogit-community/blob/60a7e08b5cc0b087b3441cd028462b865434130b/trunk/PKGBUILD#L47

That approach requires versioned lua directories though, so we would first need to make a corresponding version branch in https://github.com/conda-forge/lua-feedstock I think.

In the meantime, if you don't need multiple lua versions in the same conda environment you can use
```
conda install lua=5.1 luarocks
```

**Comment by anjos** [comment]
Closing this PR as per comments above.  Please re-open with a rebase with the latest additions if need-be.

**Pull request closed without merging**
