### PR TITLE
update to 3.7.0

### PR DESCRIPTION
**Pull request by izahn**
Checklist
* [x] Used a fork of the feedstock to propose changes
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

Just a simple version bump.

### CODE REVIEW

**Comment by izahn** [comment]
@conda-forge-admin rerender

**Comment by izahn** [comment]
I think this is ready @jerowe . I would also be happy to become a co-mantainer if you like, let me know and I'll add myself.

**Comment by izahn** [comment]
@conda-forge-admin please rerender

**Comment by xhochy** [comment]
Thanks @izahn

**Pull request merged**
